name: Build and deploy site on push

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Prepare pages artifact
        # Copy the build output (docs / build / dist) to a folder `out` for upload
        run: |
          set -e
          rm -rf out || true
          if [ -d "docs" ]; then cp -r docs out
          elif [ -d "build" ]; then cp -r build out
          elif [ -d "dist" ]; then cp -r dist out
          else
            echo "No build output found (checked docs, build, dist)"
            ls -la
            exit 1
          fi

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
